apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-website
  labels:
    k8s-app: ai-website
data:
  nginx-docs.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html/docs;
            index  index.html index.htm;
        }

        error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-deployment
  labels:
    app: ai
spec:
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
        - name: ai-nginx
          image: nginx
          ports:
            - name: web
              containerPort: 80
          volumeMounts:
            - name: www-data
              mountPath: "/usr/share/nginx/html"
            - name: conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx-docs.conf
        - name: git-sync
          image: k8s.gcr.io/git-sync:v3.1.2
          env:
            - name: GIT_SYNC_REPO
              value: "https://github.com/sachiniyer/toxic-tweets.git"
            - name: GIT_SYNC_BRANCH
              value: "main"
            - name: GIT_SYNC_ROOT
              value: /data
            - name: GIT_SYNC_DEST
              value: "docs"
            - name: GIT_SYNC_MAX_FAILURES
              value: "-1"
          volumeMounts:
            - name: www-data
              mountPath: /data

      volumes:
        - name: www-data
          emptyDir: {}
        - name: conf
          configMap:
            name: ai-website
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
  labels:
    run: nginx
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
  selector:
    app: ai
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ai-cert
  namespace: ai
spec:
  commonName: ai.sachiniyer.com
  secretName: ai-cert
  dnsNames:
    - ai.sachiniyer.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect
  namespace: ai
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ai-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: ai-redirect@kubernetescrd
spec:
  tls:
  - secretName: ai-cert
  rules:
  - host: ai.sachiniyer.com
    http:
      paths:
       - path: /
         pathType: Prefix
         backend:
           service:
             name: ai-service
             port:
               number: 80
